config/routes.rb
Myapp::Application.routes.draw do
  resources :studentorgs


  resources :scholarships
  root :to => "scholarships#index"

  authenticated :user do
    root :to => 'home#index'
  end

  
  root :to => "home#index"
  devise_for :users
  resources :users
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/scholarship.rb
class Scholarship < ActiveRecord::Base
  attr_accessible :appyurl, :descrip, :gpa, :infourl, :org, :schol
end

app/models/studentorg.rb
class Studentorg < ActiveRecord::Base
  attr_accessible :applyurl, :description, :gpa, :infourl, :name
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :role_ids, :as => :admin
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_path, :alert => exception.message
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
  end
end

app/controllers/scholarships_controller.rb
class ScholarshipsController < ApplicationController
  #before_filter :authenticate_user!
  # GET /scholarships
  # GET /scholarships.json
  def index
    @scholarships = Scholarship.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @scholarships }
    end
  end

  # GET /scholarships/1
  # GET /scholarships/1.json
  def show
    @scholarship = Scholarship.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @scholarship }
    end
  end

  # GET /scholarships/new
  # GET /scholarships/new.json
  def new
    @scholarship = Scholarship.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @scholarship }
    end
  end

  # GET /scholarships/1/edit
  def edit
    @scholarship = Scholarship.find(params[:id])
  end

  # POST /scholarships
  # POST /scholarships.json
  def create
    @scholarship = Scholarship.new(params[:scholarship])

    respond_to do |format|
      if @scholarship.save
        format.html { redirect_to @scholarship, notice: 'Scholarship was successfully created.' }
        format.json { render json: @scholarship, status: :created, location: @scholarship }
      else
        format.html { render action: "new" }
        format.json { render json: @scholarship.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /scholarships/1
  # PUT /scholarships/1.json
  def update
    @scholarship = Scholarship.find(params[:id])

    respond_to do |format|
      if @scholarship.update_attributes(params[:scholarship])
        format.html { redirect_to @scholarship, notice: 'Scholarship was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @scholarship.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /scholarships/1
  # DELETE /scholarships/1.json
  def destroy
    @scholarship = Scholarship.find(params[:id])
    @scholarship.destroy

    respond_to do |format|
      format.html { redirect_to scholarships_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/studentorgs_controller.rb
class StudentorgsController < ApplicationController
  # GET /studentorgs
  # GET /studentorgs.json
  def index
    @studentorgs = Studentorg.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @studentorgs }
    end
  end

  # GET /studentorgs/1
  # GET /studentorgs/1.json
  def show
    @studentorg = Studentorg.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @studentorg }
    end
  end

  # GET /studentorgs/new
  # GET /studentorgs/new.json
  def new
    @studentorg = Studentorg.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @studentorg }
    end
  end

  # GET /studentorgs/1/edit
  def edit
    @studentorg = Studentorg.find(params[:id])
  end

  # POST /studentorgs
  # POST /studentorgs.json
  def create
    @studentorg = Studentorg.new(params[:studentorg])

    respond_to do |format|
      if @studentorg.save
        format.html { redirect_to @studentorg, notice: 'Studentorg was successfully created.' }
        format.json { render json: @studentorg, status: :created, location: @studentorg }
      else
        format.html { render action: "new" }
        format.json { render json: @studentorg.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /studentorgs/1
  # PUT /studentorgs/1.json
  def update
    @studentorg = Studentorg.find(params[:id])

    respond_to do |format|
      if @studentorg.update_attributes(params[:studentorg])
        format.html { redirect_to @studentorg, notice: 'Studentorg was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @studentorg.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /studentorgs/1
  # DELETE /studentorgs/1.json
  def destroy
    @studentorg = Studentorg.find(params[:id])
    @studentorg.destroy

    respond_to do |format|
      format.html { redirect_to studentorgs_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def index
    authorize! :index, @user, :message => 'Not authorized as an administrator.'
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
  
  def update
    authorize! :update, @user, :message => 'Not authorized as an administrator.'
    @user = User.find(params[:id])
    if @user.update_attributes(params[:user], :as => :admin)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end
    
  def destroy
    authorize! :destroy, @user, :message => 'Not authorized as an administrator.'
    user = User.find(params[:id])
    unless user == current_user
      user.destroy
      redirect_to users_path, :notice => "User deleted."
    else
      redirect_to users_path, :notice => "Can't delete yourself."
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/scholarships_helper.rb
module ScholarshipsHelper
end

app/helpers/studentorgs_helper.rb
module StudentorgsHelper
end

app/views/home/index.html.erb
<h3>Home</h3>
<% @users.each do |user| %>
  <p>User: <%=link_to user.name, user %></p>
<% end %>

app/views/layouts/_footer.html.erb

&copy;DualDevelop 2012

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Student Opportunities", root_path, :class => 'brand' %>
<ul class="nav pull-right">
  <% if user_signed_in? %>
    <li>
    <%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %>        
    </li>
  <% else %>
    <li>
    <%= link_to 'Login', new_user_session_path %>  
    </li>
  <% end %>

  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">Account <b class="caret"></b></a>
    <ul class="dropdown-menu">
    <% if user_signed_in? %>
      <li><%= link_to 'Edit account', edit_user_registration_path %></li>
    <% if current_user.has_role? :admin %>
      <li><%= link_to 'Admin', users_path %></li>
    <% end %>
    <% else %>
      <li><%= link_to 'Sign up', new_user_registration_path %></li>
    <% end %>
    </ul>
  </li>
</ul>
  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "STJ Student Opportunities" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "STJ Student Opportunities" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <header class="navbar navbar-fixed-top navbar-inverse">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="" role="main">
      <div class="container-fluid">
        <div class="">
           <div class="row-fluid">
            <div class="span2">
              <ul class="nav nav-tabs nav-stacked">
                <li><a href="">Student Orgs</a></li>
                <li><a href="">Greek Orgs</a></li>
                <li><a href="">Academic Honor Societies</a></li>
                <li><a href="">University Honor Societies</a></li>
                <li><a href="">University Programs</a></li>
                <li><a href="">Graduate Assistantships</a></li>
                <li><a href="">Scholarships/Grants</a></li>
                <li><a href="">Job Opportunities</a></li>
                <li><a href="">Others</a></li>
                <li><a href="">Upcoming</a></li>
              <ul>
            </div>
            <div class="span10">
              <%= render 'layouts/messages' %>
              <%= yield %>

        
 
            </div>
          </div>

        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
    <footer>
            <%= render 'layouts/footer' %>
    </footer>
  </body>
</html>

app/views/scholarships/_form.html.erb
<%= simple_form_for(@scholarship) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :org %>
    <%= f.input :schol %>
    <%= f.input :descrip %>
    <%= f.input :gpa %>
    <%= f.input :infourl %>
    <%= f.input :appyurl %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/scholarships/edit.html.erb
<h1>Editing scholarship</h1>

<%= render 'form' %>

<%= link_to 'Show', @scholarship %> |
<%= link_to 'Back', scholarships_path %>

app/views/scholarships/index.html.erb
<h1 class="pageheader">Scholarships</h1>

<table class="table">
  <tr>
    <th>Organization</th>
    <th>Scholarships</th>
    <th>Description</th>
    <th>GPA</th>
    <th></th>
    <!--<th></th>
    <th></th>
    <th></th>
    <th></th>-->
  </tr>

<% @scholarships.each do |scholarship| %>
  <tr>
    <td><%= scholarship.org %></td>
    <td><%= link_to scholarship.schol, scholarship %></td>
    <td><%= scholarship.descrip %></td>
    <td><%= scholarship.gpa %></td>
    <td><div class="btn-group btn-group-vertical">
  <button class="btn"><%= link_to 'More info', scholarship.infourl %></button>
  <button class="btn"><%= link_to 'Apply Here', scholarship.appyurl %></button>
  <% if user_signed_in? %>
  <% if current_user.has_role? :admin %>
  <button class="btn"><%= link_to 'Show', scholarship %></button>
  <% end %>
  <% end %>
  <% if user_signed_in? %>
  <% if current_user.has_role? :admin %>
  <button class="btn"><%= link_to 'Edit', edit_scholarship_path(scholarship) %></button>
  <% end %>
  <% end %>
  <% if user_signed_in? %>
  <% if current_user.has_role? :admin %>
  <button class="btn"><%= link_to 'Delete', scholarship, method: :delete, data: { confirm: 'Are you sure?' } %></button>
  <% end %>
  <% end %>
</div></td>
    <!-- <td><%= link_to 'More info', scholarship.infourl %></td>
    <td><%= link_to 'Apply Here', scholarship.appyurl %></td>
    <td><%= link_to 'Show', scholarship %></td>
    <td><%= link_to 'Edit', edit_scholarship_path(scholarship) %></td>
    <td></td>
   <td><%= link_to 'Destroy', scholarship, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
  </tr>


<% end %>
</table>

<br />

<%= link_to 'New Scholarship', new_scholarship_path %>

app/views/scholarships/new.html.erb
<h1>New scholarship</h1>

<%= render 'form' %>

<%= link_to 'Back', scholarships_path %>

app/views/scholarships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Org:</b>
  <%= @scholarship.org %>
</p>

<p>
  <b>Schol:</b>
  <%= @scholarship.schol %>
</p>

<p>
  <b>Descrip:</b>
  <%= @scholarship.descrip %>
</p>

<p>
  <b>Gpa:</b>
  <%= @scholarship.gpa %>
</p>

<p>
  <b>Infourl:</b>
  <%= @scholarship.infourl %>
</p>

<p>
  <b>Appyurl:</b>
  <%= @scholarship.appyurl %>
</p>


<%= link_to 'Edit', edit_scholarship_path(@scholarship) %> |
<%= link_to 'Back', scholarships_path %>

app/views/studentorgs/_form.html.erb
<%= simple_form_for(@studentorg) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :description %>
    <%= f.input :gpa %>
    <%= f.input :infourl %>
    <%= f.input :applyurl %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/studentorgs/edit.html.erb
<h1>Editing studentorg</h1>

<%= render 'form' %>

<%= link_to 'Show', @studentorg %> |
<%= link_to 'Back', studentorgs_path %>

app/views/studentorgs/index.html.erb
<h1>Listing studentorgs</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Description</th>
    <th>Gpa</th>
    <th>Infourl</th>
    <th>Applyurl</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @studentorgs.each do |studentorg| %>
  <tr>
    <td><%= studentorg.name %></td>
    <td><%= studentorg.description %></td>
    <td><%= studentorg.gpa %></td>
    <td><%= studentorg.infourl %></td>
    <td><%= studentorg.applyurl %></td>
    <td><%= link_to 'Show', studentorg %></td>
    <td><%= link_to 'Edit', edit_studentorg_path(studentorg) %></td>
    <td><%= link_to 'Destroy', studentorg, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Studentorg', new_studentorg_path %>

app/views/studentorgs/new.html.erb
<h1>New studentorg</h1>

<%= render 'form' %>

<%= link_to 'Back', studentorgs_path %>

app/views/studentorgs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @studentorg.name %>
</p>

<p>
  <b>Description:</b>
  <%= @studentorg.description %>
</p>

<p>
  <b>Gpa:</b>
  <%= @studentorg.gpa %>
</p>

<p>
  <b>Infourl:</b>
  <%= @studentorg.infourl %>
</p>

<p>
  <b>Applyurl:</b>
  <%= @studentorg.applyurl %>
</p>


<%= link_to 'Edit', edit_studentorg_path(@studentorg) %> |
<%= link_to 'Back', studentorgs_path %>

app/views/users/_user.html.erb
<div id="role-options-<%= user.id %>" class="modal" style="display: none;">
  <%= simple_form_for user, :url => user_path(user), :html => {:method => :put, :class => 'form-horizontal' } do |f| %>
    <div class="modal-header">
      <a class="close" data-dismiss="modal">&#215;</a>
      <h3>Change Role</h3>
    </div>
    <div class="modal-body">
      <%= f.input :role_ids, :collection => Role.all, :as => :radio_buttons, :label_method => lambda {|t| t.name.titleize}, :label => false, :item_wrapper_class => 'inline' %>
    </div>
    <div class="modal-footer">
      <%= f.submit "Change Role", :class => "btn" %>
      <a class="btn" data-dismiss="modal" href="#">Close</a>
    </div>
  <% end %>
</div>

app/views/users/index.html.erb
<h3>Users</h3>
<div class="span8">
<table class="table table-condensed">
	  <thead>
      <tr>
          <th>Username</th>
          <th>Email</th>
          <th>Registered</th>
          <th>Role</th>
          <th></th>
          <th></th>                                      
      </tr>
  </thead>   
  <tbody>
  <% @users.each do |user| %>
    <tr>
        <td><%= link_to user.name, user %></td>
        <td><%= user.email %></td>
        <td><%= user.created_at.to_date %></td>
        <td><%= user.roles.first.name.titleize unless user.roles.first.nil? %></td>
        <td>
          <a data-toggle="modal" href="#role-options-<%= user.id %>" class="btn btn-mini" type="button">Change role</a>
          <%= render user %>
        </td>
        <td><%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'btn btn-mini') unless user == current_user %></td>                                       
    </tr>
  <% end %>
  </tbody>
</table>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>User: <%= @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>